namespace ExcelORM;

/// <summary>
/// A tool with which I'm working is using Aspose.Cells. I don't know if it's Aspose or this tool usage of it,
/// but Excel files generated by ClosedXML aren't compatible with it. So, on Windows I'm using Interop.Excel
/// to open and save generated file. But as I want this library to be platform independent I'm just leaving
/// this interface here. Till I'll find better solution, or ClosedXML/Aspose will become compatible.
/// </summary>
public interface IExcelConverter
{
    void MakeCompatible(string path);
}